// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ8Xp4TYEQfWPcV3-Zb4tHGsr0Bujgynk',
    appId: '1:112918552723:web:a3b47da7dd105c70296d66',
    messagingSenderId: '112918552723',
    projectId: 'agenda-1e422',
    authDomain: 'agenda-1e422.firebaseapp.com',
    storageBucket: 'agenda-1e422.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxhdAn5MbcawAkg9tWVgBOLp7Rb9TsE78',
    appId: '1:112918552723:android:5e2673120cdc7e96296d66',
    messagingSenderId: '112918552723',
    projectId: 'agenda-1e422',
    storageBucket: 'agenda-1e422.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXjweGLQt0RjhmXF1SjfWucufVhxp7Zkc',
    appId: '1:112918552723:ios:f561770ff1144fc0296d66',
    messagingSenderId: '112918552723',
    projectId: 'agenda-1e422',
    storageBucket: 'agenda-1e422.appspot.com',
    iosBundleId: 'com.example.projetoFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXjweGLQt0RjhmXF1SjfWucufVhxp7Zkc',
    appId: '1:112918552723:ios:f561770ff1144fc0296d66',
    messagingSenderId: '112918552723',
    projectId: 'agenda-1e422',
    storageBucket: 'agenda-1e422.appspot.com',
    iosBundleId: 'com.example.projetoFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ8Xp4TYEQfWPcV3-Zb4tHGsr0Bujgynk',
    appId: '1:112918552723:web:4180e01241a8ba43296d66',
    messagingSenderId: '112918552723',
    projectId: 'agenda-1e422',
    authDomain: 'agenda-1e422.firebaseapp.com',
    storageBucket: 'agenda-1e422.appspot.com',
  );
}
